import type { ProductCategoryKey } from "../src/lib/categories";

export type EffectProductSeed = {
  slug: string;
  sku: string;
  brand: string;
  nameEn: string;
  nameZh: string;
  shortDescEn: string;
  shortDescZh: string;
  descriptionEn: string;
  descriptionZh: string;
  price: number;
  image: string;
  specsEn: { label: string; value: string }[];
  specsZh: { label: string; value: string }[];
  highlightsEn: string[];
  highlightsZh: string[];
  stock: number;
  featured: boolean;
  warranty: string;
  sourceUrl: string;
  categoryKey: ProductCategoryKey;
};

const fx = (path: string) => `https://chauvetprofessional.com/wp-content/uploads/2025/10/${path}`;

/** 10 effects devices — fog, haze, CO2, strobe, bubble, snow, etc. */
export const EFFECTS_PRODUCTS: EffectProductSeed[] = [
  {
    slug: "chauvet-strike-4",
    sku: "CP-STRIKE4",
    brand: "Chauvet Professional",
    nameEn: "Strike 4",
    nameZh: "Strike 4 高亮聚光/观众灯",
    shortDescEn: "High-output blinder and audience punch light for concerts.",
    shortDescZh: "高亮聚光/观众灯，演唱会 blinder 效果。",
    descriptionEn: `Strike 4 delivers audience punch and blinder effects for concerts and touring.\n\n![Strike 4](${fx("STRIKE-4-FRONT-FEAT-1024x1024.png")})\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/strike-4/)`,
    descriptionZh: `Strike 4 高亮聚光灯，适合演唱会观众区与 blinder 效果。\n\n![Strike 4](${fx("STRIKE-4-FRONT-FEAT-1024x1024.png")})\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/strike-4/)`,
    price: 1899,
    image: fx("STRIKE-4-FRONT-FEAT-1024x1024.png"),
    specsEn: [
      { label: "Type", value: "Blinder / audience light" },
      { label: "Control", value: "DMX" },
    ],
    specsZh: [
      { label: "类型", value: "聚光 / 观众灯" },
      { label: "控制", value: "DMX" },
    ],
    highlightsEn: ["Audience blinder FX", "Tour rugged"],
    highlightsZh: ["观众区效果", "巡演级结构"],
    stock: 32,
    featured: true,
    warranty: "2 years",
    sourceUrl: "https://chauvetprofessional.com/product/strike-4/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-amhaze-stadium",
    sku: "CP-AMHAZE-ST",
    brand: "Chauvet Professional",
    nameEn: "Amhaze Stadium",
    nameZh: "Amhaze Stadium 场馆烟雾机",
    shortDescEn: "Water-based haze machine for arenas and large venues.",
    shortDescZh: "水基烟雾机，适合场馆与大型演出。",
    descriptionEn: `Amhaze Stadium produces fine haze for beam visibility in large venues.\n\n![Amhaze Stadium](${fx("amhaze_stadium-FRONT-FEAT.png")})\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/amhaze-stadium/)`,
    descriptionZh: `Amhaze Stadium 水基烟雾机，大型场馆光束可见性。\n\n![Amhaze Stadium](${fx("amhaze_stadium-FRONT-FEAT.png")})\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/amhaze-stadium/)`,
    price: 4299,
    image: fx("amhaze_stadium-FRONT-FEAT.png"),
    specsEn: [{ label: "Type", value: "Haze machine" }, { label: "Fluid", value: "Water-based haze" }],
    specsZh: [{ label: "类型", value: "烟雾机" }, { label: "耗材", value: "水基烟雾油" }],
    highlightsEn: ["Arena-scale haze", "DMX control"],
    highlightsZh: ["场馆级烟雾", "DMX 控制"],
    stock: 12,
    featured: true,
    warranty: "2 years",
    sourceUrl: "https://chauvetprofessional.com/product/amhaze-stadium/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-vesuvio-ii",
    sku: "CP-VESUVIO2",
    brand: "Chauvet Professional",
    nameEn: "Vesuvio II",
    nameZh: "Vesuvio II 纵向烟雾机",
    shortDescEn: "Vertical fog burst effect for dramatic stage reveals.",
    shortDescZh: "纵向喷烟特效，舞台出场氛围。",
    descriptionEn: `Vesuvio II creates vertical fog bursts for dramatic reveals.\n\n![Vesuvio II](${fx("vesuvio2-FRONT-FEAT.png")})\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/vesuvio-ii/)`,
    descriptionZh: `Vesuvio II 纵向喷烟，适合舞台出场与氛围营造。\n\n![Vesuvio II](${fx("vesuvio2-FRONT-FEAT.png")})\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/vesuvio-ii/)`,
    price: 1599,
    image: fx("vesuvio2-FRONT-FEAT.png"),
    specsEn: [{ label: "Type", value: "Vertical fog" }, { label: "Control", value: "DMX, manual" }],
    specsZh: [{ label: "类型", value: "纵向烟雾" }, { label: "控制", value: "DMX、手动" }],
    highlightsEn: ["Vertical burst effect", "Fast setup"],
    highlightsZh: ["纵向喷烟", "快速部署"],
    stock: 18,
    featured: false,
    warranty: "2 years",
    sourceUrl: "https://chauvetprofessional.com/product/vesuvio-ii/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-hurricane-1800-flex",
    sku: "CP-H1800F",
    brand: "Chauvet Professional",
    nameEn: "Hurricane 1800 Flex",
    nameZh: "Hurricane 1800 Flex 烟雾机",
    shortDescEn: "Flexible fog machine with high output for clubs and tours.",
    shortDescZh: "高输出灵活烟雾机，酒吧与巡演适用。",
    descriptionEn: `Hurricane 1800 Flex — high-output fog for clubs and touring.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/hurricane-1800-flex/)`,
    descriptionZh: `Hurricane 1800 Flex 高输出烟雾机。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/hurricane-1800-flex/)`,
    price: 899,
    image: fx("STRIKE-4-FRONT-FEAT-1024x1024.png"),
    specsEn: [{ label: "Output", value: "High-volume fog" }, { label: "Control", value: "DMX, timer" }],
    specsZh: [{ label: "出烟", value: "大出烟量" }, { label: "控制", value: "DMX、定时" }],
    highlightsEn: ["Tour/club staple", "Fast heat-up"],
    highlightsZh: ["酒吧巡演常备", "快速预热"],
    stock: 40,
    featured: false,
    warranty: "1 year",
    sourceUrl: "https://chauvetprofessional.com/product/hurricane-1800-flex/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-geyser-p7",
    sku: "CP-GEYSER-P7",
    brand: "Chauvet Professional",
    nameEn: "Geyser P7",
    nameZh: "Geyser P7 CO2 特效机",
    shortDescEn: "RGB CO2 jet effect with DMX control.",
    shortDescZh: "RGB CO2 气柱特效，DMX 控制。",
    descriptionEn: `Geyser P7 — RGB CO2 jet for concert FX.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/geyser-p7/)`,
    descriptionZh: `Geyser P7 RGB CO2 气柱特效。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/geyser-p7/)`,
    price: 2499,
    image: fx("vesuvio2-FRONT-FEAT.png"),
    specsEn: [{ label: "Effect", value: "CO2 jet + RGB" }, { label: "Control", value: "DMX" }],
    specsZh: [{ label: "效果", value: "CO2 气柱 + RGB" }, { label: "控制", value: "DMX" }],
    highlightsEn: ["CO2 blast FX", "RGB illumination"],
    highlightsZh: ["CO2 爆发", "RGB 照明"],
    stock: 15,
    featured: false,
    warranty: "2 years",
    sourceUrl: "https://chauvetprofessional.com/product/geyser-p7/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-f4-fog-fury",
    sku: "CP-F4-FF",
    brand: "Chauvet Professional",
    nameEn: "F4 Fog Fury",
    nameZh: "F4 Fog Fury 烟雾机",
    shortDescEn: "Compact 700W fog machine with LED illumination.",
    shortDescZh: "700W 紧凑烟雾机，带 LED 照明。",
    descriptionEn: `F4 Fog Fury — compact fog with built-in LED effects.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/f4-fog-fury/)`,
    descriptionZh: `F4 Fog Fury 紧凑烟雾机，内置 LED 效果。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/f4-fog-fury/)`,
    price: 649,
    image: fx("amhaze_stadium-FRONT-FEAT.png"),
    specsEn: [{ label: "Power", value: "700 W" }, { label: "LED", value: "Built-in RGB" }],
    specsZh: [{ label: "功率", value: "700 W" }, { label: "LED", value: "内置 RGB" }],
    highlightsEn: ["Compact rental unit", "LED fog combo"],
    highlightsZh: ["紧凑租赁", "LED+烟雾"],
    stock: 45,
    featured: false,
    warranty: "1 year",
    sourceUrl: "https://chauvetprofessional.com/product/f4-fog-fury/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-nimbus",
    sku: "CP-NIMBUS",
    brand: "Chauvet Professional",
    nameEn: "Nimbus",
    nameZh: "Nimbus 干冰烟雾机",
    shortDescEn: "Low-lying dry ice fog effect for stage and film.",
    shortDescZh: "干冰贴地烟雾，舞台与影视。",
    descriptionEn: `Nimbus creates low-lying dry ice style fog effects.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/nimbus/)`,
    descriptionZh: `Nimbus 贴地干冰烟雾效果。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/nimbus/)`,
    price: 3299,
    image: fx("vesuvio2-FRONT-FEAT.png"),
    specsEn: [{ label: "Effect", value: "Low-lying fog" }, { label: "Use", value: "Stage / film" }],
    specsZh: [{ label: "效果", value: "贴地烟雾" }, { label: "场景", value: "舞台 / 影视" }],
    highlightsEn: ["Ground-hugging fog", "DMX ready"],
    highlightsZh: ["贴地烟雾", "支持 DMX"],
    stock: 10,
    featured: false,
    warranty: "2 years",
    sourceUrl: "https://chauvetprofessional.com/product/nimbus/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-bubble-king",
    sku: "CP-BUBBLE",
    brand: "Chauvet Professional",
    nameEn: "Bubble King",
    nameZh: "Bubble King 泡泡机",
    shortDescEn: "High-output bubble machine for events and theatre.",
    shortDescZh: "高输出泡泡机，活动与剧院。",
    descriptionEn: `Bubble King — high-output bubbles for events.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/bubble-king/)`,
    descriptionZh: `Bubble King 高输出泡泡机。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/bubble-king/)`,
    price: 399,
    image: fx("amhaze_stadium-FRONT-FEAT.png"),
    specsEn: [{ label: "Type", value: "Bubble machine" }, { label: "Control", value: "DMX, wireless remote" }],
    specsZh: [{ label: "类型", value: "泡泡机" }, { label: "控制", value: "DMX、无线遥控" }],
    highlightsEn: ["Event favorite", "Wireless remote option"],
    highlightsZh: ["活动热门", "可选无线遥控"],
    stock: 35,
    featured: false,
    warranty: "1 year",
    sourceUrl: "https://chauvetprofessional.com/product/bubble-king/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-snow-machine",
    sku: "CP-SNOW",
    brand: "Chauvet Professional",
    nameEn: "Snow Machine",
    nameZh: "Snow Machine 雪花机",
    shortDescEn: "Artificial snow effect for seasonal shows and events.",
    shortDescZh: "人造雪花特效， seasonal 演出与活动。",
    descriptionEn: `Professional snow machine for seasonal and themed events.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/snow-machine/)`,
    descriptionZh: `专业雪花机，主题与 seasonal 活动。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/snow-machine/)`,
    price: 549,
    image: fx("amhaze_stadium-FRONT-FEAT.png"),
    specsEn: [{ label: "Type", value: "Snow machine" }, { label: "Control", value: "DMX, manual" }],
    specsZh: [{ label: "类型", value: "雪花机" }, { label: "控制", value: "DMX、手动" }],
    highlightsEn: ["Seasonal events", "Easy fluid fill"],
    highlightsZh: [" seasonal 活动", "易加液"],
    stock: 28,
    featured: false,
    warranty: "1 year",
    sourceUrl: "https://chauvetprofessional.com/product/snow-machine/",
    categoryKey: "effects",
  },
  {
    slug: "chauvet-mini-strobe-12led",
    sku: "CP-MSTROBE",
    brand: "Chauvet Professional",
    nameEn: "Mini Strobe 12LED",
    nameZh: "Mini Strobe 12LED 频闪灯",
    shortDescEn: "Compact LED strobe for clubs and mobile DJ.",
    shortDescZh: "紧凑 LED 频闪，酒吧与 mobile DJ。",
    descriptionEn: `Mini Strobe 12LED — compact strobe for clubs.\n\nSource: [Chauvet Professional](https://chauvetprofessional.com/product/mini-strobe-12led/)`,
    descriptionZh: `Mini Strobe 12LED 紧凑频闪灯。\n\n来源：[Chauvet Professional 官网](https://chauvetprofessional.com/product/mini-strobe-12led/)`,
    price: 199,
    image: fx("STRIKE-4-FRONT-FEAT-1024x1024.png"),
    specsEn: [{ label: "Type", value: "LED strobe" }, { label: "LEDs", value: "12 LED" }],
    specsZh: [{ label: "类型", value: "LED 频闪" }, { label: "灯珠", value: "12 LED" }],
    highlightsEn: ["Compact footprint", "Sound-active mode"],
    highlightsZh: ["紧凑体积", "声控模式"],
    stock: 60,
    featured: false,
    warranty: "1 year",
    sourceUrl: "https://chauvetprofessional.com/product/mini-strobe-12led/",
    categoryKey: "effects",
  },
];
